//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cttv
    {
        public int Ma_Cttv { get; set; }
        public string TenCongTy { get; set; }
        public string MaChungKhoan { get; set; }
        public string Email { get; set; }
        public string MoTa { get; set; }
        public string Logo { get; set; }
        public string MauNen { get; set; }
        public string MauChu { get; set; }
        public string HinhTrai { get; set; }
        public string HinhGiua { get; set; }
        public string HinhNgang { get; set; }
        public Nullable<bool> Xoa { get; set; }
    }
}
