//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class CttvThuocBang
    {
        public int Ma_CttvThuocBang { get; set; }
        public Nullable<int> Ma_CauHinhBang { get; set; }
        public Nullable<int> CauHinhBang_Cha { get; set; }
        public Nullable<int> Ma_Cttv { get; set; }
        public string CongThucDong { get; set; }
        public string DichCongThuc { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string TaoBoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CapNhatBoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
