//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public int Ma_DanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string MaDanhMuc { get; set; }
        public Nullable<int> UuTien { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string MoTa { get; set; }
        public string TaoBoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CapNhatBoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
