//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhiNhanSuCoTrongNgay
    {
        public int Ma_GhiNhanSuCoTrongNgay { get; set; }
        public Nullable<int> Ma_Cttv { get; set; }
        public Nullable<int> Ma_SoCa { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Gio { get; set; }
        public string ThietBi { get; set; }
        public Nullable<int> KhuVuc { get; set; }
        public string SuCo { get; set; }
        public string NguyenNhan { get; set; }
        public string NguoiXuLy { get; set; }
        public string KhacPhuc { get; set; }
        public string PhongNgua { get; set; }
        public string DieuChinh { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string TaoBoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CapNhatBoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<bool> Sucolon { get; set; }
        public string MaThietBi { get; set; }
        public Nullable<int> ThoiGianSuCo { get; set; }
        public Nullable<int> ThoiGianNgungEp { get; set; }
    }
}
