//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaTriBanChePham
    {
        public int Ma_GiaTriBanChePham { get; set; }
        public Nullable<int> Ma_CttvThuocBang { get; set; }
        public string GiaTri { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    }
}
