//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuuVetNguoiDung
    {
        public int Ma_LuuVet { get; set; }
        public Nullable<int> Ma_Cttv { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
        public string NguoiTao { get; set; }
        public string HanhDong { get; set; }
        public string NoiDung { get; set; }
    }
}
