//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotTieuHoaChatVatTu
    {
        public int Ma_MotTieuHoaChatVatTu { get; set; }
        public Nullable<int> Khoa_MotTieuHoaChatVatTu { get; set; }
        public string TenDong { get; set; }
        public Nullable<int> Ma_MuaVu { get; set; }
        public Nullable<int> Ma_CttvThuocBang { get; set; }
        public Nullable<double> GiaTriDinhMuc1 { get; set; }
        public Nullable<double> GiaTriDinhMuc2 { get; set; }
        public string TaoBoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CapNhatBoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
