//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public int Ma_NguoiDung { get; set; }
        public Nullable<int> Ma_Cttv { get; set; }
        public Nullable<int> Ma_ThuMuc { get; set; }
        public Nullable<int> Ma_NhomQuyen { get; set; }
        public string DanhSachCTTV { get; set; }
        public string DanhSachQuyenCapNhat { get; set; }
        public string HoTen { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<bool> Duyet { get; set; }
        public string MoTa { get; set; }
        public string TaoBoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CapNhatBoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
