//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomQuyen
    {
        public int Ma_NhomQuyen { get; set; }
        public string TenNhom { get; set; }
        public string MaNhom { get; set; }
        public string DanhSachQuyen { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string TaoBoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CapNhatBoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
