//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenNguoiDung
    {
        public int Ma_QuyenNguoiDung { get; set; }
        public Nullable<int> Ma_NguoiDung { get; set; }
        public Nullable<int> Ma_DanhMuc { get; set; }
        public Nullable<int> Ma_ThuMuc { get; set; }
    }
}
