//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiTrongD
    {
        public int Ma_TiTrong { get; set; }
        public Nullable<double> Bx { get; set; }
        public Nullable<double> d { get; set; }
    }
}
