//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFF.DTO.Entities.SmartLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraoDoiThongTin
    {
        public int Ma_TraoDoiThongTin { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
        public string NguoiThucHien { get; set; }
        public string NhanPhanHoi { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string TaoBoi { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string CapNhatBoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
